insert into message (id,text) values (100, 'The best thing about a boolean is even if you are wrong, you are only off by a bit. - Anonymous');
insert into message (id,text) values (110, 'The city’s central computer told you?  R2D2, you know better than to trust a strange computer! - C-3PO');
insert into message (id,text) values (120, 'I’ll create a GUI interface using Visual Basic. See if I can track an IP address. - CSI');
insert into message (id,text) values (130, 'Each time I shut my computer down, I throw my head back in maniacal laughter and scream "Fool! I was only using you!" - Bridger Winegar');
insert into message (id,text) values (140, 'The problem with quotes on the internet is you can never be certain they’re authentic. - Abraham Lincoln');
insert into message (id,text) values (150, 'The Internet?  Is that thing still around? - Home Simpson');
insert into message (id,text) values (160, 'If debugging is the process of removing software bugs, then programming must be the process of putting them in. - Edsger Dijkstra');
insert into message (id,text) values (170, 'Walking on water and developing software from a specification are easy if both are frozen. - Edward V Berard');
insert into message (id,text) values (180, 'Any fool can write code that a computer can understand. Good programmers write code that humans can understand. - Martin Fowler');
insert into message (id,text) values (190, 'Before software can be reusable it first has to be usable. - Ralph Johnson');
insert into message (id,text) values (200, 'Without requirements or design, programming is the art of adding bugs to an empty text file. - Louis Srygley');
insert into message (id,text) values (210, 'The question of whether computers can think is like the question of whether submarines can swim. - Edsger W. Dijkstra');
insert into message (id,text) values (220, 'Treat your password like your toothbrush. Don’t let anybody else use it, and get a new one every six months. - Clifford Stoll');
insert into message (id,text) values (230, 'To err is human, but to really foul things up you need a computer. - Paul Ehrlich');